import type { ComponentType, CSSProperties } from 'react';
import { Icon } from '../components/ui/Icon';

export type MaterialIconProps = {
  size?: number;
  className?: string;
  strokeWidth?: number;
  fill?: string;
  color?: string;
  style?: CSSProperties;
};

export type MaterialIcon = ComponentType<MaterialIconProps>;

const createIcon = (name: string, defaultFilled = false): MaterialIcon => {
  const Component = ({ size = 20, className, fill, color, style }: MaterialIconProps) => (
    <Icon
      name={name}
      size={size}
      className={className}
      filled={Boolean(fill) || defaultFilled}
      style={{ color: color || fill, ...style }}
    />
  );
  Component.displayName = name;
  return Component;
};

// Lucide-compatible names → Material Symbols
export const LayoutDashboard = createIcon('dashboard');
export const UsersRound = createIcon('group');
export const Users = createIcon('groups');
export const User = createIcon('person');
export const UserRound = createIcon('account_circle');
export const UserCheck = createIcon('how_to_reg');
export const BookOpen = createIcon('menu_book');
export const Tags = createIcon('category');
export const Tag = createIcon('sell');
export const Route = createIcon('route');
export const Radio = createIcon('sensors');
export const CreditCard = createIcon('credit_card');
export const Gift = createIcon('card_giftcard');
export const Award = createIcon('workspace_premium');
export const Star = createIcon('star');
export const Bell = createIcon('notifications');
export const BellOff = createIcon('notifications_off');
export const Headphones = createIcon('headset_mic');
export const Wallet = createIcon('account_balance_wallet');
export const AccountBalance = createIcon('account_balance');
export const BarChart3 = createIcon('bar_chart');
export const LiveTv = createIcon('live_tv');
export const CoPresent = createIcon('co_present');
export const Redeem = createIcon('redeem');
export const SupportAgent = createIcon('support_agent');
export const Reviews = createIcon('reviews');
export const Settings = createIcon('settings');
export const Settings2 = createIcon('tune');
export const Menu = createIcon('menu');
export const MenuOpen = createIcon('menu_open');
export const ChevronDown = createIcon('expand_more');
export const ChevronUp = createIcon('expand_less');
export const LogOut = createIcon('logout');
export const Download = createIcon('download');
export const Plus = createIcon('add');
export const Shield = createIcon('shield');
export const ShieldOff = createIcon('gpp_bad');
export const ShieldCheck = createIcon('verified_user');
export const Search = createIcon('search');
export const RotateCcw = createIcon('refresh');
export const X = createIcon('close');
export const Inbox = createIcon('inbox');
export const CheckCircle2 = createIcon('check_circle');
export const CheckCircle = createIcon('check_circle');
export const XCircle = createIcon('cancel');
export const AlertCircle = createIcon('error');
export const Info = createIcon('info');
export const AlertTriangle = createIcon('warning');
export const ArrowRight = createIcon('arrow_back');
export const ArrowLeft = createIcon('arrow_forward');
export const ArrowDown = createIcon('keyboard_arrow_down');
export const ArrowUp = createIcon('keyboard_arrow_up');
export const ArrowDownToLine = createIcon('download');
export const ArrowDownLeft = createIcon('south_west');
export const ArrowUpRight = createIcon('north_east');
export const Home = createIcon('home');
export const Lock = createIcon('lock');
export const Unlock = createIcon('lock_open');
export const Play = createIcon('play_arrow');
export const PlayCircle = createIcon('play_circle');
export const Clock = createIcon('schedule');
export const Clock3 = createIcon('schedule');
export const Calendar = createIcon('calendar_month');
export const CalendarDays = createIcon('calendar_today');
export const Mail = createIcon('mail');
export const Phone = createIcon('phone');
export const MessageSquare = createIcon('chat');
export const MessageSquarePlus = createIcon('add_comment');
export const MessagesSquare = createIcon('forum');
export const GraduationCap = createIcon('school');
export const Layers = createIcon('layers');
export const FolderTree = createIcon('account_tree');
export const Ticket = createIcon('confirmation_number');
export const Receipt = createIcon('receipt_long');
export const TrendingUp = createIcon('trending_up');
export const TrendingDown = createIcon('trending_down');
export const DollarSign = createIcon('payments');
export const RefreshCw = createIcon('sync');
export const Send = createIcon('send');
export const Copy = createIcon('content_copy');
export const ExternalLink = createIcon('open_in_new');
export const Trash2 = createIcon('delete');
export const Edit = createIcon('edit');
export const Pencil = createIcon('edit');
export const Save = createIcon('save');
export const ThumbsUp = createIcon('thumb_up');
export const Video = createIcon('videocam');
export const FilePlus = createIcon('note_add');
export const Upload = createIcon('upload');
export const GripVertical = createIcon('drag_indicator');
export const ClipboardList = createIcon('checklist');
export const Image = createIcon('image');
export const ImagePlus = createIcon('add_photo_alternate');
export const Palette = createIcon('palette');
export const Globe = createIcon('language');
export const Building = createIcon('apartment');
export const Eye = createIcon('visibility');
export const EyeOff = createIcon('visibility_off');
export const Filter = createIcon('filter_list');
export const MoreVertical = createIcon('more_vert');
export const HelpCircle = createIcon('help');
export const Zap = createIcon('bolt');
export const Target = createIcon('track_changes');
export const BookMarked = createIcon('bookmark');
export const Circle = createIcon('circle');
export const Check = createIcon('check');
export const Minus = createIcon('remove');
export const Loader2 = createIcon('progress_activity');
export const DarkMode = createIcon('dark_mode');
export const LightMode = createIcon('light_mode');
export const Crown = createIcon('workspace_premium');
export const MessageCircle = createIcon('forum');
export const PlusCircle = createIcon('add_circle');
export const Sparkles = createIcon('auto_awesome');
export const MapPin = createIcon('location_on');
export const Share2 = createIcon('share');
export const Heart = createIcon('favorite', true);
export const List = createIcon('list');
export const Grid = createIcon('grid_view');
export const Table2 = createIcon('table_rows');
export const FileText = createIcon('description');
export const Monitor = createIcon('monitor');
export const Mic = createIcon('mic');
export const Pause = createIcon('pause');
export const SkipForward = createIcon('skip_next');
export const SkipBack = createIcon('skip_previous');
export const Volume2 = createIcon('volume_up');
export const Maximize = createIcon('fullscreen');
export const Minimize = createIcon('fullscreen_exit');
export const CircleHelp = createIcon('help');
export const BadgeCheck = createIcon('verified');
export const Banknote = createIcon('account_balance');
export const Percent = createIcon('percent');
export const Hash = createIcon('tag');
export const Link2 = createIcon('link');
export const Paperclip = createIcon('attach_file');
export const Smile = createIcon('sentiment_satisfied');
export const Flag = createIcon('flag');
export const Ban = createIcon('block');
export const UserX = createIcon('person_off');
export const UserPlus = createIcon('person_add');
export const History = createIcon('history');
export const LayoutList = createIcon('view_list');
export const LayoutGrid = createIcon('grid_view');
export const CircleDot = createIcon('fiber_manual_record');
export const Megaphone = createIcon('campaign');
export const Store = createIcon('storefront');
export const ShoppingCart = createIcon('shopping_cart');
export const Package = createIcon('inventory_2');
export const QrCode = createIcon('qr_code');
export const Scan = createIcon('document_scanner');
export const SlidersHorizontal = createIcon('tune');
export const Wand2 = createIcon('auto_fix_high');
export const PenLine = createIcon('edit_note');
export const CirclePlus = createIcon('add_circle');
export const CircleMinus = createIcon('remove_circle');
export const CircleCheck = createIcon('check_circle');
export const CircleX = createIcon('highlight_off');
export const ChevronLeft = createIcon('chevron_right');
export const ChevronRight = createIcon('chevron_left');
export const Wrench = createIcon('build');
export const Briefcase = createIcon('work');
export const KeyRound = createIcon('key');
export const ListChecks = createIcon('playlist_add_check');
export const CheckCheck = createIcon('done_all');

export type LucideIcon = MaterialIcon;
